<?php

// Data functions (insert, update, delete, form) for table BOOK

// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

function BOOK_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('BOOK');
	if(!$arrPerm[1]){
		return false;
	}

	$data['teams'] = makeSafe($_REQUEST['teams']);
		if($data['teams'] == empty_lookup_value){ $data['teams'] = ''; }
	$data['id_no'] = makeSafe($_REQUEST['id_no']);
		if($data['id_no'] == empty_lookup_value){ $data['id_no'] = ''; }
	$data['phone'] = makeSafe($_REQUEST['id_no']);
		if($data['phone'] == empty_lookup_value){ $data['phone'] = ''; }
	$data['name'] = makeSafe($_REQUEST['id_no']);
		if($data['name'] == empty_lookup_value){ $data['name'] = ''; }
	$data['mode'] = makeSafe($_REQUEST['mode']);
		if($data['mode'] == empty_lookup_value){ $data['mode'] = ''; }
	$data['mpesa'] = makeSafe($_REQUEST['mode']);
		if($data['mpesa'] == empty_lookup_value){ $data['mpesa'] = ''; }
	$data['paypal'] = makeSafe($_REQUEST['mode']);
		if($data['paypal'] == empty_lookup_value){ $data['paypal'] = ''; }
	$data['bank'] = makeSafe($_REQUEST['mode']);
		if($data['bank'] == empty_lookup_value){ $data['bank'] = ''; }
	$data['select'] = makeSafe($_REQUEST['select']);
		if($data['select'] == empty_lookup_value){ $data['select'] = ''; }
	$data['enters'] = makeSafe($_REQUEST['enters']);
		if($data['enters'] == empty_lookup_value){ $data['enters'] = ''; }
	$data['book_date'] = mysql_datetime($_REQUEST['book_date']);
		if($data['book_date'] == empty_lookup_value){ $data['book_date'] = ''; }
	if($data['book_date'] == '') $data['book_date'] = "1";

	// hook: BOOK_before_insert
	if(function_exists('BOOK_before_insert')){
		$args=array();
		if(!BOOK_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `BOOK` set       `teams`=' . (($data['teams'] !== '' && $data['teams'] !== NULL) ? "'{$data['teams']}'" : 'NULL') . ', `id_no`=' . (($data['id_no'] !== '' && $data['id_no'] !== NULL) ? "'{$data['id_no']}'" : 'NULL') . ', `phone`=' . (($data['phone'] !== '' && $data['phone'] !== NULL) ? "'{$data['phone']}'" : 'NULL') . ', `name`=' . (($data['name'] !== '' && $data['name'] !== NULL) ? "'{$data['name']}'" : 'NULL') . ', `mode`=' . (($data['mode'] !== '' && $data['mode'] !== NULL) ? "'{$data['mode']}'" : 'NULL') . ', `mpesa`=' . (($data['mpesa'] !== '' && $data['mpesa'] !== NULL) ? "'{$data['mpesa']}'" : 'NULL') . ', `paypal`=' . (($data['paypal'] !== '' && $data['paypal'] !== NULL) ? "'{$data['paypal']}'" : 'NULL') . ', `bank`=' . (($data['bank'] !== '' && $data['bank'] !== NULL) ? "'{$data['bank']}'" : 'NULL') . ', `select`=' . (($data['select'] !== '' && $data['select'] !== NULL) ? "'{$data['select']}'" : 'NULL') . ', `enters`=' . (($data['enters'] !== '' && $data['enters'] !== NULL) ? "'{$data['enters']}'" : 'NULL') . ', `book_date`=' . (($data['book_date'] !== '' && $data['book_date'] !== NULL) ? "'{$data['book_date']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"BOOK_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: BOOK_after_insert
	if(function_exists('BOOK_after_insert')){
		$res = sql("select * from `BOOK` where `ID`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!BOOK_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('BOOK', $recID, getLoggedMemberID());

	return $recID;
}

function BOOK_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('BOOK');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='BOOK' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='BOOK' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: BOOK_before_delete
	if(function_exists('BOOK_before_delete')){
		$args=array();
		if(!BOOK_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `BOOK` where `ID`='$selected_id'", $eo);

	// hook: BOOK_after_delete
	if(function_exists('BOOK_after_delete')){
		$args=array();
		BOOK_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='BOOK' and pkValue='$selected_id'", $eo);
}

function BOOK_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('BOOK');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='BOOK' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='BOOK' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['teams'] = makeSafe($_REQUEST['teams']);
		if($data['teams'] == empty_lookup_value){ $data['teams'] = ''; }
	$data['id_no'] = makeSafe($_REQUEST['id_no']);
		if($data['id_no'] == empty_lookup_value){ $data['id_no'] = ''; }
	$data['phone'] = makeSafe($_REQUEST['id_no']);
		if($data['phone'] == empty_lookup_value){ $data['phone'] = ''; }
	$data['name'] = makeSafe($_REQUEST['id_no']);
		if($data['name'] == empty_lookup_value){ $data['name'] = ''; }
	$data['mode'] = makeSafe($_REQUEST['mode']);
		if($data['mode'] == empty_lookup_value){ $data['mode'] = ''; }
	$data['mpesa'] = makeSafe($_REQUEST['mode']);
		if($data['mpesa'] == empty_lookup_value){ $data['mpesa'] = ''; }
	$data['paypal'] = makeSafe($_REQUEST['mode']);
		if($data['paypal'] == empty_lookup_value){ $data['paypal'] = ''; }
	$data['bank'] = makeSafe($_REQUEST['mode']);
		if($data['bank'] == empty_lookup_value){ $data['bank'] = ''; }
	$data['select'] = makeSafe($_REQUEST['select']);
		if($data['select'] == empty_lookup_value){ $data['select'] = ''; }
	$data['enters'] = makeSafe($_REQUEST['enters']);
		if($data['enters'] == empty_lookup_value){ $data['enters'] = ''; }
	$data['book_date'] = mysql_datetime($_REQUEST['book_date']);
		if($data['book_date'] == empty_lookup_value){ $data['book_date'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: BOOK_before_update
	if(function_exists('BOOK_before_update')){
		$args=array();
		if(!BOOK_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `BOOK` set       `teams`=' . (($data['teams'] !== '' && $data['teams'] !== NULL) ? "'{$data['teams']}'" : 'NULL') . ', `id_no`=' . (($data['id_no'] !== '' && $data['id_no'] !== NULL) ? "'{$data['id_no']}'" : 'NULL') . ', `phone`=' . (($data['phone'] !== '' && $data['phone'] !== NULL) ? "'{$data['phone']}'" : 'NULL') . ', `name`=' . (($data['name'] !== '' && $data['name'] !== NULL) ? "'{$data['name']}'" : 'NULL') . ', `mode`=' . (($data['mode'] !== '' && $data['mode'] !== NULL) ? "'{$data['mode']}'" : 'NULL') . ', `mpesa`=' . (($data['mpesa'] !== '' && $data['mpesa'] !== NULL) ? "'{$data['mpesa']}'" : 'NULL') . ', `paypal`=' . (($data['paypal'] !== '' && $data['paypal'] !== NULL) ? "'{$data['paypal']}'" : 'NULL') . ', `bank`=' . (($data['bank'] !== '' && $data['bank'] !== NULL) ? "'{$data['bank']}'" : 'NULL') . ', `select`=' . (($data['select'] !== '' && $data['select'] !== NULL) ? "'{$data['select']}'" : 'NULL') . ', `enters`=' . (($data['enters'] !== '' && $data['enters'] !== NULL) ? "'{$data['enters']}'" : 'NULL') . ', `book_date`=' . (($data['book_date'] !== '' && $data['book_date'] !== NULL) ? "'{$data['book_date']}'" : 'NULL') . " where `ID`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="BOOK_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: BOOK_after_update
	if(function_exists('BOOK_after_update')){
		$res = sql("SELECT * FROM `BOOK` WHERE `ID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['ID'];
		$args = array();
		if(!BOOK_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='BOOK' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function BOOK_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('BOOK');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_teams = thisOr(undo_magic_quotes($_REQUEST['filterer_teams']), '');
	$filterer_id_no = thisOr(undo_magic_quotes($_REQUEST['filterer_id_no']), '');
	$filterer_mode = thisOr(undo_magic_quotes($_REQUEST['filterer_mode']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: teams
	$combo_teams = new DataCombo;
	// combobox: id_no
	$combo_id_no = new DataCombo;
	// combobox: mode
	$combo_mode = new DataCombo;
	// combobox: select
	$combo_select = new Combo;
	$combo_select->ListType = 0;
	$combo_select->MultipleSeparator = ', ';
	$combo_select->ListBoxHeight = 10;
	$combo_select->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/BOOK.select.csv')){
		$select_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/BOOK.select.csv')));
		$combo_select->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($select_data)));
		$combo_select->ListData = $combo_select->ListItem;
	}else{
		$combo_select->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("mpesa;;paypal;;bankwire;;")));
		$combo_select->ListData = $combo_select->ListItem;
	}
	$combo_select->SelectName = 'select';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='BOOK' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='BOOK' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `BOOK` where `ID`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'BOOK_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_teams->SelectedData = $row['teams'];
		$combo_id_no->SelectedData = $row['id_no'];
		$combo_mode->SelectedData = $row['mode'];
		$combo_select->SelectedData = $row['select'];
	}else{
		$combo_teams->SelectedData = $filterer_teams;
		$combo_id_no->SelectedData = $filterer_id_no;
		$combo_mode->SelectedData = $filterer_mode;
		$combo_select->SelectedText = ( $_REQUEST['FilterField'][1]=='10' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_teams->HTML = '<span id="teams-container' . $rnd1 . '"></span><input type="hidden" name="teams" id="teams' . $rnd1 . '" value="' . html_attr($combo_teams->SelectedData) . '">';
	$combo_teams->MatchText = '<span id="teams-container-readonly' . $rnd1 . '"></span><input type="hidden" name="teams" id="teams' . $rnd1 . '" value="' . html_attr($combo_teams->SelectedData) . '">';
	$combo_id_no->HTML = '<span id="id_no-container' . $rnd1 . '"></span><input type="hidden" name="id_no" id="id_no' . $rnd1 . '" value="' . html_attr($combo_id_no->SelectedData) . '">';
	$combo_id_no->MatchText = '<span id="id_no-container-readonly' . $rnd1 . '"></span><input type="hidden" name="id_no" id="id_no' . $rnd1 . '" value="' . html_attr($combo_id_no->SelectedData) . '">';
	$combo_mode->HTML = '<span id="mode-container' . $rnd1 . '"></span><input type="hidden" name="mode" id="mode' . $rnd1 . '" value="' . html_attr($combo_mode->SelectedData) . '">';
	$combo_mode->MatchText = '<span id="mode-container-readonly' . $rnd1 . '"></span><input type="hidden" name="mode" id="mode' . $rnd1 . '" value="' . html_attr($combo_mode->SelectedData) . '">';
	$combo_select->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_teams__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['teams'] : $filterer_teams); ?>"};
		AppGini.current_id_no__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['id_no'] : $filterer_id_no); ?>"};
		AppGini.current_mode__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['mode'] : $filterer_mode); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(teams_reload__RAND__) == 'function') teams_reload__RAND__();
				if(typeof(id_no_reload__RAND__) == 'function') id_no_reload__RAND__();
				if(typeof(mode_reload__RAND__) == 'function') mode_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function teams_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#teams-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_teams__RAND__.value, t: 'BOOK', f: 'teams' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="teams"]').val(resp.results[0].id);
							$j('[id=teams-container-readonly__RAND__]').html('<span id="teams-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=EVENTS_view_parent]').hide(); }else{ $j('.btn[id=EVENTS_view_parent]').show(); }


							if(typeof(teams_update_autofills__RAND__) == 'function') teams_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'BOOK', f: 'teams' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_teams__RAND__.value = e.added.id;
				AppGini.current_teams__RAND__.text = e.added.text;
				$j('[name="teams"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=EVENTS_view_parent]').hide(); }else{ $j('.btn[id=EVENTS_view_parent]').show(); }


				if(typeof(teams_update_autofills__RAND__) == 'function') teams_update_autofills__RAND__();
			});

			if(!$j("#teams-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_teams__RAND__.value, t: 'BOOK', f: 'teams' },
					success: function(resp){
						$j('[name="teams"]').val(resp.results[0].id);
						$j('[id=teams-container-readonly__RAND__]').html('<span id="teams-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=EVENTS_view_parent]').hide(); }else{ $j('.btn[id=EVENTS_view_parent]').show(); }

						if(typeof(teams_update_autofills__RAND__) == 'function') teams_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_teams__RAND__.value, t: 'BOOK', f: 'teams' },
				success: function(resp){
					$j('[id=teams-container__RAND__], [id=teams-container-readonly__RAND__]').html('<span id="teams-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=EVENTS_view_parent]').hide(); }else{ $j('.btn[id=EVENTS_view_parent]').show(); }

					if(typeof(teams_update_autofills__RAND__) == 'function') teams_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function id_no_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#id_no-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_id_no__RAND__.value, t: 'BOOK', f: 'id_no' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="id_no"]').val(resp.results[0].id);
							$j('[id=id_no-container-readonly__RAND__]').html('<span id="id_no-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=FANS_view_parent]').hide(); }else{ $j('.btn[id=FANS_view_parent]').show(); }


							if(typeof(id_no_update_autofills__RAND__) == 'function') id_no_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'BOOK', f: 'id_no' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_id_no__RAND__.value = e.added.id;
				AppGini.current_id_no__RAND__.text = e.added.text;
				$j('[name="id_no"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=FANS_view_parent]').hide(); }else{ $j('.btn[id=FANS_view_parent]').show(); }


				if(typeof(id_no_update_autofills__RAND__) == 'function') id_no_update_autofills__RAND__();
			});

			if(!$j("#id_no-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_id_no__RAND__.value, t: 'BOOK', f: 'id_no' },
					success: function(resp){
						$j('[name="id_no"]').val(resp.results[0].id);
						$j('[id=id_no-container-readonly__RAND__]').html('<span id="id_no-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=FANS_view_parent]').hide(); }else{ $j('.btn[id=FANS_view_parent]').show(); }

						if(typeof(id_no_update_autofills__RAND__) == 'function') id_no_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_id_no__RAND__.value, t: 'BOOK', f: 'id_no' },
				success: function(resp){
					$j('[id=id_no-container__RAND__], [id=id_no-container-readonly__RAND__]').html('<span id="id_no-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=FANS_view_parent]').hide(); }else{ $j('.btn[id=FANS_view_parent]').show(); }

					if(typeof(id_no_update_autofills__RAND__) == 'function') id_no_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function mode_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#mode-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_mode__RAND__.value, t: 'BOOK', f: 'mode' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="mode"]').val(resp.results[0].id);
							$j('[id=mode-container-readonly__RAND__]').html('<span id="mode-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=payments_view_parent]').hide(); }else{ $j('.btn[id=payments_view_parent]').show(); }


							if(typeof(mode_update_autofills__RAND__) == 'function') mode_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'BOOK', f: 'mode' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_mode__RAND__.value = e.added.id;
				AppGini.current_mode__RAND__.text = e.added.text;
				$j('[name="mode"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=payments_view_parent]').hide(); }else{ $j('.btn[id=payments_view_parent]').show(); }


				if(typeof(mode_update_autofills__RAND__) == 'function') mode_update_autofills__RAND__();
			});

			if(!$j("#mode-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_mode__RAND__.value, t: 'BOOK', f: 'mode' },
					success: function(resp){
						$j('[name="mode"]').val(resp.results[0].id);
						$j('[id=mode-container-readonly__RAND__]').html('<span id="mode-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=payments_view_parent]').hide(); }else{ $j('.btn[id=payments_view_parent]').show(); }

						if(typeof(mode_update_autofills__RAND__) == 'function') mode_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_mode__RAND__.value, t: 'BOOK', f: 'mode' },
				success: function(resp){
					$j('[id=mode-container__RAND__], [id=mode-container-readonly__RAND__]').html('<span id="mode-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=payments_view_parent]').hide(); }else{ $j('.btn[id=payments_view_parent]').show(); }

					if(typeof(mode_update_autofills__RAND__) == 'function') mode_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/BOOK_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/BOOK_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'BOOK details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return BOOK_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return BOOK_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return BOOK_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#teams').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#teams_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#id_no').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#id_no_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#mode').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#mode_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#select').replaceWith('<div class=\"form-control-static\" id=\"select\">' + (jQuery('#select').val() || '') + '</div>'); jQuery('#select-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#enters').replaceWith('<div class=\"form-control-static\" id=\"enters\">' + (jQuery('#enters').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#book_date').parents('.input-group').replaceWith('<div class=\"form-control-static\" id=\"book_date\">' + (jQuery('#book_date').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$locale = isset($Translation['datetimepicker locale']) ? ", locale: '{$Translation['datetimepicker locale']}'" : '';
		$jsEditable .= "\tjQuery('#book_date').addClass('always_shown').parents('.input-group').datetimepicker({ toolbarPlacement: 'top', sideBySide: true, showClear: true, showTodayButton: true, showClose: true, icons: { close: 'glyphicon glyphicon-ok' }, format: AppGini.datetimeFormat('dt') {$locale} });";
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(teams)%%>', $combo_teams->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(teams)%%>', $combo_teams->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(teams)%%>', urlencode($combo_teams->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(id_no)%%>', $combo_id_no->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(id_no)%%>', $combo_id_no->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(id_no)%%>', urlencode($combo_id_no->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(mode)%%>', $combo_mode->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(mode)%%>', $combo_mode->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(mode)%%>', urlencode($combo_mode->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(select)%%>', $combo_select->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(select)%%>', $combo_select->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'teams' => array('EVENTS', 'Event'), 'id_no' => array('FANS', 'Id no'), 'mode' => array('payments', 'Mode of payment'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(ID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(teams)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(id_no)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(mode)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(select)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(enters)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(book_date)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', safe_html($urow['ID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', html_attr($row['ID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode($urow['ID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(teams)%%>', safe_html($urow['teams']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(teams)%%>', html_attr($row['teams']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(teams)%%>', urlencode($urow['teams']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id_no)%%>', safe_html($urow['id_no']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id_no)%%>', html_attr($row['id_no']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_no)%%>', urlencode($urow['id_no']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(mode)%%>', safe_html($urow['mode']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(mode)%%>', html_attr($row['mode']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(mode)%%>', urlencode($urow['mode']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(select)%%>', safe_html($urow['select']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(select)%%>', html_attr($row['select']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(select)%%>', urlencode($urow['select']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(enters)%%>', safe_html($urow['enters']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(enters)%%>', html_attr($row['enters']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(enters)%%>', urlencode($urow['enters']), $templateCode);
		$templateCode = str_replace('<%%VALUE(book_date)%%>', app_datetime($row['book_date'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(book_date)%%>', urlencode(app_datetime($urow['book_date'], 'dt')), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(ID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(teams)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(teams)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(id_no)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_no)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(mode)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(mode)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(select)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(select)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(enters)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(enters)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(book_date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(book_date)%%>', urlencode('1'), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tid_no_update_autofills$rnd1 = function(){\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'BOOK_autofill.php?rnd1=$rnd1&mfk=id_no&id=' + encodeURIComponent('".addslashes($row['id_no'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'BOOK_autofill.php?rnd1=$rnd1&mfk=id_no&id=' + encodeURIComponent(AppGini.current_id_no{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#id_no$rnd1').prop('disabled', true); \$j('#id_noLoading').html('<img src=loading.gif align=top>'); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#id_no$rnd1').prop('disabled', false); " : "\$j('#id_no$rnd1').prop('disabled', true); ")."\$j('#id_noLoading').html(''); \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#id_no_caption').length) \$j('#id_no_caption').click(function(){ /* */ id_no_update_autofills$rnd1(); });\n";

	$templateCode .= "\tmode_update_autofills$rnd1 = function(){\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'BOOK_autofill.php?rnd1=$rnd1&mfk=mode&id=' + encodeURIComponent('".addslashes($row['mode'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'BOOK_autofill.php?rnd1=$rnd1&mfk=mode&id=' + encodeURIComponent(AppGini.current_mode{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#mode$rnd1').prop('disabled', true); \$j('#modeLoading').html('<img src=loading.gif align=top>'); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#mode$rnd1').prop('disabled', false); " : "\$j('#mode$rnd1').prop('disabled', true); ")."\$j('#modeLoading').html(''); \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#mode_caption').length) \$j('#mode_caption').click(function(){ /* */ mode_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('BOOK');
	if($selected_id){
		$jdata = get_joined_record('BOOK', $selected_id);
		if($jdata === false) $jdata = get_defaults('BOOK');
		$rdata = $row;
	}
	$templateCode .= loadView('BOOK-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: BOOK_dv
	if(function_exists('BOOK_dv')){
		$args=array();
		BOOK_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>