<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/BOOKING.php");
	include("$currDir/BOOKING_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('BOOKING');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "BOOKING";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`BOOKING`.`id`" => "id",
		"`BOOKING`.`Teams`" => "Teams",
		"`BOOKING`.`venue`" => "venue",
		"if(`BOOKING`.`date`,date_format(`BOOKING`.`date`,'%m/%d/%Y'),'')" => "date",
		"TIME_FORMAT(`BOOKING`.`endtime`, '%r')" => "endtime",
		"`BOOKING`.`slots`" => "slots"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`BOOKING`.`id`',
		2 => 2,
		3 => 3,
		4 => '`BOOKING`.`date`',
		5 => '`BOOKING`.`endtime`',
		6 => 6
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`BOOKING`.`id`" => "id",
		"`BOOKING`.`Teams`" => "Teams",
		"`BOOKING`.`venue`" => "venue",
		"if(`BOOKING`.`date`,date_format(`BOOKING`.`date`,'%m/%d/%Y'),'')" => "date",
		"TIME_FORMAT(`BOOKING`.`endtime`, '%r')" => "endtime",
		"`BOOKING`.`slots`" => "slots"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`BOOKING`.`id`" => "ID",
		"`BOOKING`.`Teams`" => "Teams",
		"`BOOKING`.`venue`" => "Venue",
		"`BOOKING`.`date`" => "Date",
		"`BOOKING`.`endtime`" => "Endtime",
		"`BOOKING`.`slots`" => "Slots Available"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`BOOKING`.`id`" => "id",
		"`BOOKING`.`Teams`" => "Teams",
		"`BOOKING`.`venue`" => "venue",
		"if(`BOOKING`.`date`,date_format(`BOOKING`.`date`,'%m/%d/%Y'),'')" => "date",
		"TIME_FORMAT(`BOOKING`.`endtime`, '%r')" => "endtime",
		"`BOOKING`.`slots`" => "slots"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`BOOKING` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "BOOKING_view.php";
	$x->RedirectAfterInsert = "BOOKING_view.php?SelectedID=#ID#";
	$x->TableTitle = "BOOKING";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`BOOKING`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150);
	$x->ColCaption = array("Teams", "Venue", "Date", "Endtime", "Slots Available");
	$x->ColFieldName = array('Teams', 'venue', 'date', 'endtime', 'slots');
	$x->ColNumber  = array(2, 3, 4, 5, 6);

	// template paths below are based on the app main directory
	$x->Template = 'templates/BOOKING_templateTV.html';
	$x->SelectedTemplate = 'templates/BOOKING_templateTVS.html';
	$x->TemplateDV = 'templates/BOOKING_templateDV.html';
	$x->TemplateDVP = 'templates/BOOKING_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `BOOKING`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='BOOKING' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `BOOKING`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='BOOKING' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`BOOKING`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: BOOKING_init
	$render=TRUE;
	if(function_exists('BOOKING_init')){
		$args=array();
		$render=BOOKING_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: BOOKING_header
	$headerCode='';
	if(function_exists('BOOKING_header')){
		$args=array();
		$headerCode=BOOKING_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: BOOKING_footer
	$footerCode='';
	if(function_exists('BOOKING_footer')){
		$args=array();
		$footerCode=BOOKING_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>