<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/BOOK.php");
	include("$currDir/BOOK_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('BOOK');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "BOOK";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`BOOK`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`EVENTS1`.`teams`) || CHAR_LENGTH(if(`EVENTS1`.`date`,date_format(`EVENTS1`.`date`,'%m/%d/%Y %h:%i %p'),'')), CONCAT_WS('',   `EVENTS1`.`teams`, '>>', if(`EVENTS1`.`date`,date_format(`EVENTS1`.`date`,'%m/%d/%Y %h:%i %p'),'')), '') /* Event */" => "teams",
		"IF(    CHAR_LENGTH(`FANS1`.`id_no`), CONCAT_WS('',   `FANS1`.`id_no`), '') /* Id no */" => "id_no",
		"IF(    CHAR_LENGTH(`FANS1`.`phone`), CONCAT_WS('',   `FANS1`.`phone`), '') /* your Phone number */" => "phone",
		"IF(    CHAR_LENGTH(`FANS1`.`Name`), CONCAT_WS('',   `FANS1`.`Name`), '') /* Name */" => "name",
		"IF(    CHAR_LENGTH(`payments1`.`channels`), CONCAT_WS('',   `payments1`.`channels`), '') /* Mode of payment */" => "mode",
		"IF(    CHAR_LENGTH(`payments1`.`mpesa`), CONCAT_WS('',   `payments1`.`mpesa`), '') /* Mpesa Till number */" => "mpesa",
		"IF(    CHAR_LENGTH(`payments1`.`paypal`), CONCAT_WS('',   `payments1`.`paypal`), '') /* Paypal pay channel */" => "paypal",
		"IF(    CHAR_LENGTH(`payments1`.`bank`), CONCAT_WS('',   `payments1`.`bank`), '') /* Bank wire */" => "bank",
		"`BOOK`.`select`" => "select",
		"`BOOK`.`enters`" => "enters",
		"if(`BOOK`.`book_date`,date_format(`BOOK`.`book_date`,'%m/%d/%Y %h:%i %p'),'')" => "book_date"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`BOOK`.`ID`',
		2 => 2,
		3 => '`FANS1`.`id_no`',
		4 => '`FANS1`.`phone`',
		5 => '`FANS1`.`Name`',
		6 => '`payments1`.`channels`',
		7 => '`payments1`.`mpesa`',
		8 => '`payments1`.`paypal`',
		9 => '`payments1`.`bank`',
		10 => 10,
		11 => 11,
		12 => '`BOOK`.`book_date`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`BOOK`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`EVENTS1`.`teams`) || CHAR_LENGTH(if(`EVENTS1`.`date`,date_format(`EVENTS1`.`date`,'%m/%d/%Y %h:%i %p'),'')), CONCAT_WS('',   `EVENTS1`.`teams`, '>>', if(`EVENTS1`.`date`,date_format(`EVENTS1`.`date`,'%m/%d/%Y %h:%i %p'),'')), '') /* Event */" => "teams",
		"IF(    CHAR_LENGTH(`FANS1`.`id_no`), CONCAT_WS('',   `FANS1`.`id_no`), '') /* Id no */" => "id_no",
		"IF(    CHAR_LENGTH(`FANS1`.`phone`), CONCAT_WS('',   `FANS1`.`phone`), '') /* your Phone number */" => "phone",
		"IF(    CHAR_LENGTH(`FANS1`.`Name`), CONCAT_WS('',   `FANS1`.`Name`), '') /* Name */" => "name",
		"IF(    CHAR_LENGTH(`payments1`.`channels`), CONCAT_WS('',   `payments1`.`channels`), '') /* Mode of payment */" => "mode",
		"IF(    CHAR_LENGTH(`payments1`.`mpesa`), CONCAT_WS('',   `payments1`.`mpesa`), '') /* Mpesa Till number */" => "mpesa",
		"IF(    CHAR_LENGTH(`payments1`.`paypal`), CONCAT_WS('',   `payments1`.`paypal`), '') /* Paypal pay channel */" => "paypal",
		"IF(    CHAR_LENGTH(`payments1`.`bank`), CONCAT_WS('',   `payments1`.`bank`), '') /* Bank wire */" => "bank",
		"`BOOK`.`select`" => "select",
		"`BOOK`.`enters`" => "enters",
		"if(`BOOK`.`book_date`,date_format(`BOOK`.`book_date`,'%m/%d/%Y %h:%i %p'),'')" => "book_date"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`BOOK`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`EVENTS1`.`teams`) || CHAR_LENGTH(if(`EVENTS1`.`date`,date_format(`EVENTS1`.`date`,'%m/%d/%Y %h:%i %p'),'')), CONCAT_WS('',   `EVENTS1`.`teams`, '>>', if(`EVENTS1`.`date`,date_format(`EVENTS1`.`date`,'%m/%d/%Y %h:%i %p'),'')), '') /* Event */" => "Event",
		"IF(    CHAR_LENGTH(`FANS1`.`id_no`), CONCAT_WS('',   `FANS1`.`id_no`), '') /* Id no */" => "Id no",
		"IF(    CHAR_LENGTH(`FANS1`.`phone`), CONCAT_WS('',   `FANS1`.`phone`), '') /* your Phone number */" => "your Phone number",
		"IF(    CHAR_LENGTH(`FANS1`.`Name`), CONCAT_WS('',   `FANS1`.`Name`), '') /* Name */" => "Name",
		"IF(    CHAR_LENGTH(`payments1`.`channels`), CONCAT_WS('',   `payments1`.`channels`), '') /* Mode of payment */" => "Mode of payment",
		"IF(    CHAR_LENGTH(`payments1`.`mpesa`), CONCAT_WS('',   `payments1`.`mpesa`), '') /* Mpesa Till number */" => "Mpesa Till number",
		"IF(    CHAR_LENGTH(`payments1`.`paypal`), CONCAT_WS('',   `payments1`.`paypal`), '') /* Paypal pay channel */" => "Paypal pay channel",
		"IF(    CHAR_LENGTH(`payments1`.`bank`), CONCAT_WS('',   `payments1`.`bank`), '') /* Bank wire */" => "Bank wire",
		"`BOOK`.`select`" => "Select mode",
		"`BOOK`.`enters`" => "Enter confirmation code",
		"`BOOK`.`book_date`" => "Booking date"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`BOOK`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`EVENTS1`.`teams`) || CHAR_LENGTH(if(`EVENTS1`.`date`,date_format(`EVENTS1`.`date`,'%m/%d/%Y %h:%i %p'),'')), CONCAT_WS('',   `EVENTS1`.`teams`, '>>', if(`EVENTS1`.`date`,date_format(`EVENTS1`.`date`,'%m/%d/%Y %h:%i %p'),'')), '') /* Event */" => "teams",
		"IF(    CHAR_LENGTH(`FANS1`.`id_no`), CONCAT_WS('',   `FANS1`.`id_no`), '') /* Id no */" => "id_no",
		"IF(    CHAR_LENGTH(`FANS1`.`phone`), CONCAT_WS('',   `FANS1`.`phone`), '') /* your Phone number */" => "phone",
		"IF(    CHAR_LENGTH(`FANS1`.`Name`), CONCAT_WS('',   `FANS1`.`Name`), '') /* Name */" => "name",
		"IF(    CHAR_LENGTH(`payments1`.`channels`), CONCAT_WS('',   `payments1`.`channels`), '') /* Mode of payment */" => "mode",
		"IF(    CHAR_LENGTH(`payments1`.`mpesa`), CONCAT_WS('',   `payments1`.`mpesa`), '') /* Mpesa Till number */" => "mpesa",
		"IF(    CHAR_LENGTH(`payments1`.`paypal`), CONCAT_WS('',   `payments1`.`paypal`), '') /* Paypal pay channel */" => "paypal",
		"IF(    CHAR_LENGTH(`payments1`.`bank`), CONCAT_WS('',   `payments1`.`bank`), '') /* Bank wire */" => "bank",
		"`BOOK`.`select`" => "select",
		"`BOOK`.`enters`" => "enters",
		"if(`BOOK`.`book_date`,date_format(`BOOK`.`book_date`,'%m/%d/%Y %h:%i %p'),'')" => "book_date"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'teams' => 'Event', 'id_no' => 'Id no', 'mode' => 'Mode of payment');

	$x->QueryFrom = "`BOOK` LEFT JOIN `EVENTS` as EVENTS1 ON `EVENTS1`.`id`=`BOOK`.`teams` LEFT JOIN `FANS` as FANS1 ON `FANS1`.`ID`=`BOOK`.`id_no` LEFT JOIN `payments` as payments1 ON `payments1`.`id`=`BOOK`.`mode` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "BOOK_view.php";
	$x->RedirectAfterInsert = "BOOK_view.php?SelectedID=#ID#";
	$x->TableTitle = "BOOK";
	$x->TableIcon = "resources/table_icons/book_edit.png";
	$x->PrimaryKey = "`BOOK`.`ID`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Event", "Id no", "your Phone number", "Name", "Mode of payment", "Mpesa Till number", "Paypal pay channel", "Bank wire", "Select mode", "Enter confirmation code", "Booking date");
	$x->ColFieldName = array('teams', 'id_no', 'phone', 'name', 'mode', 'mpesa', 'paypal', 'bank', 'select', 'enters', 'book_date');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12);

	// template paths below are based on the app main directory
	$x->Template = 'templates/BOOK_templateTV.html';
	$x->SelectedTemplate = 'templates/BOOK_templateTVS.html';
	$x->TemplateDV = 'templates/BOOK_templateDV.html';
	$x->TemplateDVP = 'templates/BOOK_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `BOOK`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='BOOK' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `BOOK`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='BOOK' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`BOOK`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: BOOK_init
	$render=TRUE;
	if(function_exists('BOOK_init')){
		$args=array();
		$render=BOOK_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: BOOK_header
	$headerCode='';
	if(function_exists('BOOK_header')){
		$args=array();
		$headerCode=BOOK_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: BOOK_footer
	$footerCode='';
	if(function_exists('BOOK_footer')){
		$args=array();
		$footerCode=BOOK_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>