<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('BOOK');
	if(!$table_perms[0]){ die('// Access denied!'); }

	$mfk = $_GET['mfk'];
	$id = makeSafe($_GET['id']);
	$rnd1 = intval($_GET['rnd1']); if(!$rnd1) $rnd1 = '';

	if(!$mfk){
		die('// No js code available!');
	}

	switch($mfk){

		case 'id_no':
			if(!$id){
				?>
				$j('#phone<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#name<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `FANS`.`ID` as 'ID', `FANS`.`Name` as 'Name', `FANS`.`phone` as 'phone', `FANS`.`id_no` as 'id_no' FROM `FANS`  WHERE `FANS`.`ID`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#phone<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['phone']))); ?>&nbsp;');
			$j('#name<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['Name']))); ?>&nbsp;');
			<?php
			break;

		case 'mode':
			if(!$id){
				?>
				$j('#mpesa<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#paypal<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#bank<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `payments`.`id` as 'id', `payments`.`channels` as 'channels', `payments`.`mpesa` as 'mpesa', `payments`.`paypal` as 'paypal', `payments`.`bank` as 'bank' FROM `payments`  WHERE `payments`.`id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#mpesa<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['mpesa']))); ?>&nbsp;');
			$j('#paypal<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['paypal']))); ?>&nbsp;');
			$j('#bank<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['bank']))); ?>&nbsp;');
			<?php
			break;


	}

?>