<?php

// Data functions (insert, update, delete, form) for table RESERVE

// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

function RESERVE_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('RESERVE');
	if(!$arrPerm[1]){
		return false;
	}

	$data['Event'] = makeSafe($_REQUEST['Event']);
		if($data['Event'] == empty_lookup_value){ $data['Event'] = ''; }
	$data['assigned_to'] = makeSafe($_REQUEST['assigned_to']);
		if($data['assigned_to'] == empty_lookup_value){ $data['assigned_to'] = ''; }
	$data['time'] = makeSafe($_REQUEST['time']);
		if($data['time'] == empty_lookup_value){ $data['time'] = ''; }
	$data['time'] = time24($data['time']);
	$data['status'] = makeSafe($_REQUEST['status']);
		if($data['status'] == empty_lookup_value){ $data['status'] = ''; }
	$data['Amount_paid'] = makeSafe($_REQUEST['Amount_paid']);
		if($data['Amount_paid'] == empty_lookup_value){ $data['Amount_paid'] = ''; }
	$data['mode'] = makeSafe($_REQUEST['mode']);
		if($data['mode'] == empty_lookup_value){ $data['mode'] = ''; }

	// hook: RESERVE_before_insert
	if(function_exists('RESERVE_before_insert')){
		$args=array();
		if(!RESERVE_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `RESERVE` set       `Event`=' . (($data['Event'] !== '' && $data['Event'] !== NULL) ? "'{$data['Event']}'" : 'NULL') . ', `assigned_to`=' . (($data['assigned_to'] !== '' && $data['assigned_to'] !== NULL) ? "'{$data['assigned_to']}'" : 'NULL') . ', `time`=' . (($data['time'] !== '' && $data['time'] !== NULL) ? "'{$data['time']}'" : 'NULL') . ', `status`=' . (($data['status'] !== '' && $data['status'] !== NULL) ? "'{$data['status']}'" : 'NULL') . ', `Amount_paid`=' . (($data['Amount_paid'] !== '' && $data['Amount_paid'] !== NULL) ? "'{$data['Amount_paid']}'" : 'NULL') . ', `mode`=' . (($data['mode'] !== '' && $data['mode'] !== NULL) ? "'{$data['mode']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"RESERVE_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: RESERVE_after_insert
	if(function_exists('RESERVE_after_insert')){
		$res = sql("select * from `RESERVE` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!RESERVE_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('RESERVE', $recID, getLoggedMemberID());

	return $recID;
}

function RESERVE_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('RESERVE');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='RESERVE' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='RESERVE' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: RESERVE_before_delete
	if(function_exists('RESERVE_before_delete')){
		$args=array();
		if(!RESERVE_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `RESERVE` where `id`='$selected_id'", $eo);

	// hook: RESERVE_after_delete
	if(function_exists('RESERVE_after_delete')){
		$args=array();
		RESERVE_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='RESERVE' and pkValue='$selected_id'", $eo);
}

function RESERVE_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('RESERVE');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='RESERVE' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='RESERVE' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Event'] = makeSafe($_REQUEST['Event']);
		if($data['Event'] == empty_lookup_value){ $data['Event'] = ''; }
	$data['assigned_to'] = makeSafe($_REQUEST['assigned_to']);
		if($data['assigned_to'] == empty_lookup_value){ $data['assigned_to'] = ''; }
	$data['time'] = makeSafe($_REQUEST['time']);
		if($data['time'] == empty_lookup_value){ $data['time'] = ''; }
	$data['time'] = time24($data['time']);
	$data['status'] = makeSafe($_REQUEST['status']);
		if($data['status'] == empty_lookup_value){ $data['status'] = ''; }
	$data['Amount_paid'] = makeSafe($_REQUEST['Amount_paid']);
		if($data['Amount_paid'] == empty_lookup_value){ $data['Amount_paid'] = ''; }
	$data['mode'] = makeSafe($_REQUEST['mode']);
		if($data['mode'] == empty_lookup_value){ $data['mode'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: RESERVE_before_update
	if(function_exists('RESERVE_before_update')){
		$args=array();
		if(!RESERVE_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `RESERVE` set       `Event`=' . (($data['Event'] !== '' && $data['Event'] !== NULL) ? "'{$data['Event']}'" : 'NULL') . ', `assigned_to`=' . (($data['assigned_to'] !== '' && $data['assigned_to'] !== NULL) ? "'{$data['assigned_to']}'" : 'NULL') . ', `time`=' . (($data['time'] !== '' && $data['time'] !== NULL) ? "'{$data['time']}'" : 'NULL') . ', `status`=' . (($data['status'] !== '' && $data['status'] !== NULL) ? "'{$data['status']}'" : 'NULL') . ', `Amount_paid`=' . (($data['Amount_paid'] !== '' && $data['Amount_paid'] !== NULL) ? "'{$data['Amount_paid']}'" : 'NULL') . ', `mode`=' . (($data['mode'] !== '' && $data['mode'] !== NULL) ? "'{$data['mode']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="RESERVE_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: RESERVE_after_update
	if(function_exists('RESERVE_after_update')){
		$res = sql("SELECT * FROM `RESERVE` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!RESERVE_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='RESERVE' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function RESERVE_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('RESERVE');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_Event = thisOr(undo_magic_quotes($_REQUEST['filterer_Event']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Event
	$combo_Event = new DataCombo;
	// combobox: status
	$combo_status = new Combo;
	$combo_status->ListType = 0;
	$combo_status->MultipleSeparator = ', ';
	$combo_status->ListBoxHeight = 10;
	$combo_status->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/RESERVE.status.csv')){
		$status_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/RESERVE.status.csv')));
		$combo_status->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($status_data)));
		$combo_status->ListData = $combo_status->ListItem;
	}else{
		$combo_status->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("paid;;pending;;cancled;;")));
		$combo_status->ListData = $combo_status->ListItem;
	}
	$combo_status->SelectName = 'status';
	// combobox: mode
	$combo_mode = new Combo;
	$combo_mode->ListType = 0;
	$combo_mode->MultipleSeparator = ', ';
	$combo_mode->ListBoxHeight = 10;
	$combo_mode->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/RESERVE.mode.csv')){
		$mode_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/RESERVE.mode.csv')));
		$combo_mode->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($mode_data)));
		$combo_mode->ListData = $combo_mode->ListItem;
	}else{
		$combo_mode->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("Mpesa;;bankwire;;cash;;paypal;;")));
		$combo_mode->ListData = $combo_mode->ListItem;
	}
	$combo_mode->SelectName = 'mode';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='RESERVE' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='RESERVE' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `RESERVE` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'RESERVE_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_Event->SelectedData = $row['Event'];
		$combo_status->SelectedData = $row['status'];
		$combo_mode->SelectedData = $row['mode'];
	}else{
		$combo_Event->SelectedData = $filterer_Event;
		$combo_status->SelectedText = ( $_REQUEST['FilterField'][1]=='5' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_mode->SelectedText = ( $_REQUEST['FilterField'][1]=='7' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_Event->HTML = '<span id="Event-container' . $rnd1 . '"></span><input type="hidden" name="Event" id="Event' . $rnd1 . '" value="' . html_attr($combo_Event->SelectedData) . '">';
	$combo_Event->MatchText = '<span id="Event-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Event" id="Event' . $rnd1 . '" value="' . html_attr($combo_Event->SelectedData) . '">';
	$combo_status->Render();
	$combo_mode->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Event__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Event'] : $filterer_Event); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(Event_reload__RAND__) == 'function') Event_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Event_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#Event-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Event__RAND__.value, t: 'RESERVE', f: 'Event' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Event"]').val(resp.results[0].id);
							$j('[id=Event-container-readonly__RAND__]').html('<span id="Event-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=EVENTS_view_parent]').hide(); }else{ $j('.btn[id=EVENTS_view_parent]').show(); }


							if(typeof(Event_update_autofills__RAND__) == 'function') Event_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'RESERVE', f: 'Event' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_Event__RAND__.value = e.added.id;
				AppGini.current_Event__RAND__.text = e.added.text;
				$j('[name="Event"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=EVENTS_view_parent]').hide(); }else{ $j('.btn[id=EVENTS_view_parent]').show(); }


				if(typeof(Event_update_autofills__RAND__) == 'function') Event_update_autofills__RAND__();
			});

			if(!$j("#Event-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Event__RAND__.value, t: 'RESERVE', f: 'Event' },
					success: function(resp){
						$j('[name="Event"]').val(resp.results[0].id);
						$j('[id=Event-container-readonly__RAND__]').html('<span id="Event-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=EVENTS_view_parent]').hide(); }else{ $j('.btn[id=EVENTS_view_parent]').show(); }

						if(typeof(Event_update_autofills__RAND__) == 'function') Event_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Event__RAND__.value, t: 'RESERVE', f: 'Event' },
				success: function(resp){
					$j('[id=Event-container__RAND__], [id=Event-container-readonly__RAND__]').html('<span id="Event-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=EVENTS_view_parent]').hide(); }else{ $j('.btn[id=EVENTS_view_parent]').show(); }

					if(typeof(Event_update_autofills__RAND__) == 'function') Event_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/RESERVE_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/RESERVE_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'RESERVE details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return RESERVE_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return RESERVE_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return RESERVE_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#Event').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Event_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#assigned_to').replaceWith('<div class=\"form-control-static\" id=\"assigned_to\">' + (jQuery('#assigned_to').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#time').replaceWith('<div class=\"form-control-static\" id=\"time\">' + (jQuery('#time').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#status').replaceWith('<div class=\"form-control-static\" id=\"status\">' + (jQuery('#status').val() || '') + '</div>'); jQuery('#status-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#Amount_paid').replaceWith('<div class=\"form-control-static\" id=\"Amount_paid\">' + (jQuery('#Amount_paid').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#mode').replaceWith('<div class=\"form-control-static\" id=\"mode\">' + (jQuery('#mode').val() || '') + '</div>'); jQuery('#mode-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('#time').addClass('always_shown').timepicker({ defaultTime: false, showSeconds: true, showMeridian: true, showInputs: false, disableFocus: true, minuteStep: 5 });";
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Event)%%>', $combo_Event->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Event)%%>', $combo_Event->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Event)%%>', urlencode($combo_Event->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(status)%%>', $combo_status->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(status)%%>', $combo_status->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(mode)%%>', $combo_mode->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(mode)%%>', $combo_mode->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'Event' => array('EVENTS', 'Event'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Event)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(assigned_to)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(time)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(status)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Amount_paid)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(mode)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Event)%%>', safe_html($urow['Event']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Event)%%>', html_attr($row['Event']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Event)%%>', urlencode($urow['Event']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(assigned_to)%%>', safe_html($urow['assigned_to']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(assigned_to)%%>', html_attr($row['assigned_to']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(assigned_to)%%>', urlencode($urow['assigned_to']), $templateCode);
		$templateCode = str_replace('<%%VALUE(time)%%>', time12(html_attr($row['time'])), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(time)%%>', urlencode(time12($urow['time'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', safe_html($urow['status']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', html_attr($row['status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode($urow['status']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Amount_paid)%%>', safe_html($urow['Amount_paid']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Amount_paid)%%>', html_attr($row['Amount_paid']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Amount_paid)%%>', urlencode($urow['Amount_paid']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(mode)%%>', safe_html($urow['mode']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(mode)%%>', html_attr($row['mode']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(mode)%%>', urlencode($urow['mode']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Event)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Event)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(assigned_to)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(assigned_to)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(time)%%>', time12(''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(time)%%>', urlencode(time12('')), $templateCode);
		$templateCode = str_replace('<%%VALUE(status)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Amount_paid)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Amount_paid)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(mode)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(mode)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('RESERVE');
	if($selected_id){
		$jdata = get_joined_record('RESERVE', $selected_id);
		if($jdata === false) $jdata = get_defaults('RESERVE');
		$rdata = $row;
	}
	$templateCode .= loadView('RESERVE-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: RESERVE_dv
	if(function_exists('RESERVE_dv')){
		$args=array();
		RESERVE_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>